function data()
return {
	"Jalan Jenderal Sudirman",
	"Jalan M.H. Thamrin",
	"Jalan Gatot Subroto",
	"Jalan Rasuna Said",
	"Jalan Gajah Mada",
	"Jalan Hayam Wuruk",
	"Jalan Asia Afrika",
	"Jalan Malioboro",
	"Jalan Diponegoro",
	"Jalan Imam Bonjol",
	"Jalan Jenderal Ahmad Yani",
	"Jalan Pemuda",
	"Jalan Pahlawan",
	"Jalan Merdeka",
	"Jalan Veteran",
	"Jalan Kartini",
	"Jalan Juanda",
	"Jalan Wahid Hasyim",
	"Jalan Kebon Sirih",
	"Jalan Sabang",
	"Jalan Jaksa",
	"Jalan Braga",
	"Jalan Dago",
	"Jalan Riau",
	"Jalan Setiabudi",
	"Jalan Sukajadi",
	"Jalan Pasteur",
	"Jalan Antapani",
	"Jalan Kopo",
	"Jalan Buah Batu",
	"Jalan Soekarno-Hatta",
	"Jalan S. Parman",
	"Jalan M.T. Haryono",
	"Jalan D.I. Panjaitan",
	"Jalan Letjen Suprapto",
	"Jalan H. Samanhudi",
	"Jalan Fachrudin",
	"Jalan Agus Salim",
	"Jalan Raden Saleh",
	"Jalan Cikini",
	"Jalan Kramat Raya",
	"Jalan Salemba",
	"Jalan Matraman",
}
end
