function data()
return {
	"Jalan Jenderal Sudirman",
	"Jalan M.H. Thamrin",
	"Jalan Gatot Subroto",
	"Jalan Rasuna Said",
	"Jalan Gajah Mada",
	"Jalan Hayam Wuruk",
	"Jalan Asia Afrika",
	"Jalan Malioboro",
	"Jalan Diponegoro",
	"Jalan Imam Bonjol",
	"Jalan Jenderal Ahmad Yani",
	"Jalan Pemuda",
	"Jalan Pahlawan",
	"Jalan Merdeka",
	"Jalan Veteran",
	"Jalan Kartini",
	"Jalan Juanda",
	"Jalan Wahid Hasyim",
	"Jalan Kebon Sirih",
	"Jalan Sabang",
	"Jalan Jaksa",
	"Jalan Braga",
	"Jalan Dago",
	"Jalan Riau",
	"Jalan Setiabudi",
	"Jalan Sukajadi",
	"Jalan Pasteur",
	"Jalan Antapani",
	"Jalan Kopo",
	"Jalan Buah Batu",
	"Jalan Soekarno-Hatta",
	"Jalan S. Parman",
	"Jalan M.T. Haryono",
	"Jalan D.I. Panjaitan",
	"Jalan Letjen Suprapto",
	"Jalan H. Samanhudi",
	"Jalan Fachrudin",
	"Jalan Agus Salim",
	"Jalan Raden Saleh",
	"Jalan Cikini",
	"Jalan Kramat Raya",
	"Jalan Salemba",
	"Jalan Matraman",
	"Jalan Ahmad Dahlan",
	"Jalan KH Hasyim Ashari",
	"Jalan Teuku Umar",
	"Jalan Cut Nyak Dien",
	"Jalan Pattimura",
	"Jalan Pangeran Antasari",
	"Jalan Sultan Agung",
	"Jalan Sultan Hasanuddin",
	"Jalan Dipatiukur",
	"Jalan HOS Cokroaminoto",
	"Jalan Basuki Rahmat",
	"Jalan Ahmad Yani",
	"Jalan Dr. Sutomo",
	"Jalan Kiai Haji Mas Mansyur",
	"Jalan KH Zainul Arifin",
	"Jalan Prof. Dr. Supomo",
	"Jalan Pajajaran",
	"Jalan Cendrawasih",
	"Jalan Merpati",
	"Jalan Rajawali",
	"Jalan Kutilang",
	"Jalan Melati",
	"Jalan Anggrek",
	"Jalan Kenanga",
	"Jalan Mawar",
	"Jalan Dahlia",
	"Jalan Cemara",
	"Jalan Flamboyan",
	"Jalan Bougenville",
}
end
